package com.ash7nly.monolith.mapper;


import com.ash7nly.monolith.dto.request.TrackShipmentDTO;
import com.ash7nly.monolith.dto.request.TrackingHistoryDTO;
import com.ash7nly.monolith.entity.Delivery;
import com.ash7nly.monolith.entity.Driver;
import com.ash7nly.monolith.entity.ShipmentEntity;
import com.ash7nly.monolith.entity.TrackingHistoryEntity;
import org.springframework.stereotype.Component;

import java.util.UUID;

@Component
public class TrackingMapper {
    public TrackShipmentDTO toDTO(ShipmentEntity entity){

        TrackShipmentDTO shipment = new TrackShipmentDTO();
        shipment.setPickupAdress(entity.getPickupAdress());
        shipment.setDeliveryAdress(entity.getDeliveryAdress());
        shipment.setMerchantId(entity.getMerchantId());
        shipment.setStatus(entity.getStatus());
        shipment.setCreatedAt(entity.getCreatedAt());
        shipment.setUpdatedAt(entity.getUpdatedAt());
        shipment.setTrackingNumber(entity.getTrackingNumber()); // be careful if ID is autogenerated
        return shipment;
    }

    public TrackingHistoryDTO toDTO(TrackingHistoryEntity history) {
        TrackingHistoryDTO dto = new TrackingHistoryDTO();

        dto.setStatus(history.getShipmentStatus());
        dto.setTimestamp(history.getTimestamp());
        return dto;
    }


    public String generateTrackingCode() {
        String uuid = UUID.randomUUID().toString();
        String uniqueBase = uuid.replace("-", "").toUpperCase(); // 32 chars
        String uniqueCode = uniqueBase.substring(0, 12);

        return "TRK" + uniqueCode;
    }
}