package com.ash7nly.shipment.Mapper;

import com.ash7nly.shipment.DTOs.TrackShipmentDTO;
import com.ash7nly.shipment.Entity.ShipmentEntity;
import org.springframework.stereotype.Component;
import java.util.UUID;

@Component
public class TrackingMapper {
    public TrackShipmentDTO toDTO(ShipmentEntity entity){

        TrackShipmentDTO shipment = new TrackShipmentDTO();
        shipment.setPickupAdress(entity.getPickupAdress());
        shipment.setDeliveryAdress(entity.getDeliveryAdress());
        shipment.setMerchantId(entity.getMerchantId());
        shipment.setStatus(entity.getStatus());
        shipment.setCreatedAt(entity.getCreatedAt());
        shipment.setUpdatedAt(entity.getUpdatedAt());
        shipment.setTrackingNumber(entity.getTrackingNumber()); // be careful if ID is autogenerated
        return shipment;
    }

    public String generateTrackingCode() {
        return UUID.randomUUID().toString();
    }
}
